### ISSUE TITLE
gradle 질문 드립니다.

### ISSUE THREAD

**Issue by jovian-philip** [Charlezz/FastCampusSNS#1]
안녕하세요, 초보여서 질문드립니다. 패스트캠퍼스 안드로이드 힐트 강의 듣고 있습니다.
Part1. 의존성 주입과 Hilt 사용법에서 Ch5. Hilt의 API 활용 및 예제 실습에서
04. Hilt를 이용한 의존성 주입예제를 시청중인데,

그래서 github에서 소스를 다운받아 안드로이드 스튜디오에서 열어보니까

Build file '/Users/AndroidStudioProjects/hilt_sns/FastCampusSNS/build.gradle.kts' line: 14

Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by build file 'build.gradle.kts'

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.InvalidUserCodeException: Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by build file 'build.gradle.kts'
	at org.gradle.internal.management.DefaultDependencyResolutionManagement.repoMutationDisallowedOnProject(DefaultDependencyResolutionManagement.java:199)
	at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:262)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:113)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:251)
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.access$101(DefaultArtifactRepositoryContainer.java:35)
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.lambda$new$0(DefaultArtifactRepositoryContainer.java:38)
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addWithUniqueName(DefaultArtifactRepositoryContainer.java:101)
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addRepository(DefaultArtifactRepositoryContainer.java:89)
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addRepository(DefaultArtifactRepositoryContainer.java:84)
	at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.google(DefaultRepositoryHandler.java:151)
	at Build_gradle$1.invoke(build.gradle.kts:14)
	at Build_gradle$1.invoke(build.gradle.kts:13)
	at org.gradle.kotlin.dsl.ProjectExtensionsKt.repositories(ProjectExtensions.kt:159)
	at Build_gradle.<init>(build.gradle.kts:13)
	
에러가 나타나서요..

혹시

setting.gradle.kts에
pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "FastcampusSNS"
include(":app")
include(":practice")
//include(":domain")
//include(":presentation")
//include(":data")
//include(":assistedinjection")
//include(":hiltextensionapp")
//include(":annotations")
//include(":compiler")
//include(":DynamicFeature")

이렇게 주석처리해야하나요?

app build.kts에도
@Suppress("DSL_SCOPE_VIOLATION") // TODO: Remove once KTIJ-19369 is fixed
plugins {
    alias(libs.plugins.com.android.application)
    alias(libs.plugins.org.jetbrains.kotlin.android)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.fastcampus.hilt)
}

android {
    namespace = "kr.co.fastcampus.sns"
    compileSdk = 34

    defaultConfig {
        applicationId = "kr.co.fastcampus.sns"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "kr.co.fastcampus.sns.CustomRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.4.3"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
//    dynamicFeatures += setOf(":DynamicFeature")
    kapt {
        correctErrorTypes = true
    }
}

dependencies {

//    implementation(project(":domain"))
//    implementation(project(":data"))
//    implementation(project(":presentation"))

    implementation(libs.core.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.activity.compose)
    implementation(platform(libs.compose.bom))
    implementation(libs.ui)
    implementation(libs.ui.graphics)
    implementation(libs.ui.tooling.preview)
    implementation(libs.material3)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.espresso.core)
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.ui.test.junit4)
    debugImplementation(libs.ui.tooling)
    debugImplementation(libs.ui.test.manifest)

    implementation(libs.datastore)

    implementation(libs.retrofit)
    implementation(libs.retrofit.converter.serialization)

    implementation(libs.kotlinx.serialization.json)
    implementation(libs.okhttp)

    // for instrumentation tests
    androidTestImplementation("com.google.dagger:hilt-android-testing:2.48.1")
    kaptAndroidTest("com.google.dagger:hilt-compiler:2.48.1")

    // for Local unit tests
    testImplementation("com.google.dagger:hilt-android-testing:2.48.1")
    kaptTest("com.google.dagger:hilt-compiler:2.48.1")

    testImplementation("org.robolectric:robolectric:4.11.1")

    // hilt+ work
    implementation("androidx.work:work-runtime-ktx:2.9.0")
    implementation("androidx.hilt:hilt-work:1.2.0")
    kapt("androidx.hilt:hilt-compiler:1.2.0")

}이렇게 주석처리해야하나요?

주석처리해도 주석처리 안해도 에러가 나타나고 있어서 어떻게 하면 좋죠?

**Comment by Charlezz** [comment]
주석할 필요 없이, 클립별로 손쉽게 따라가실 수 있도록 커밋을 생성해두었습니다.
예를 들어 Part1, Chapter5, clip4 영상에 대한 소스코드를 확인하시고 싶으시다면 아래와 같이 head를 옮기실 수 있습니다.

`$ git checkout cbac962`

문제가 지속될 경우 프로젝트 환경이 다음과 같은지 확인부탁드립니다.

- Android Studio Giraffe 2022.3.1
- AGP 8.1
- JDK 17
- Android SDK API Level 34
- Hilt 2.48.1
